const PERMISSIONS = require("./permissions");

const ROLE_PERMISSIONS = {
  owner: Object.values(PERMISSIONS),

  admin: [
    PERMISSIONS.ORGANIZATION_VIEW,
    PERMISSIONS.ORGANIZATION_UPDATE,

    PERMISSIONS.CUSTOMER_CREATE,
    PERMISSIONS.CUSTOMER_VIEW,
    PERMISSIONS.CUSTOMER_UPDATE,
    PERMISSIONS.CUSTOMER_DELETE,

    PERMISSIONS.SERVICE_CREATE,
    PERMISSIONS.SERVICE_VIEW,
    PERMISSIONS.SERVICE_UPDATE,
    PERMISSIONS.SERVICE_DELETE,

    PERMISSIONS.STAFF_CREATE,
    PERMISSIONS.STAFF_VIEW,
    PERMISSIONS.STAFF_UPDATE,
    PERMISSIONS.STAFF_DELETE,

    PERMISSIONS.BOOKING_CREATE,
    PERMISSIONS.BOOKING_VIEW,
    PERMISSIONS.BOOKING_UPDATE,
    PERMISSIONS.BOOKING_DELETE,

    PERMISSIONS.JOB_CREATE,
    PERMISSIONS.JOB_VIEW,
    PERMISSIONS.JOB_UPDATE,
    PERMISSIONS.JOB_DELETE,

    PERMISSIONS.QUOTE_CREATE,
    PERMISSIONS.QUOTE_VIEW,
    PERMISSIONS.QUOTE_UPDATE,
    PERMISSIONS.QUOTE_DELETE,

    PERMISSIONS.INVOICE_CREATE,
    PERMISSIONS.INVOICE_VIEW,
    PERMISSIONS.INVOICE_UPDATE,
    PERMISSIONS.INVOICE_DELETE,

    PERMISSIONS.PAYMENT_CREATE,
    PERMISSIONS.PAYMENT_VIEW,

    PERMISSIONS.ANALYTICS_VIEW,
  ],

  manager: [
    PERMISSIONS.ORGANIZATION_VIEW,

    PERMISSIONS.CUSTOMER_CREATE,
    PERMISSIONS.CUSTOMER_VIEW,
    PERMISSIONS.CUSTOMER_UPDATE,

    PERMISSIONS.SERVICE_VIEW,

    PERMISSIONS.STAFF_VIEW,

    PERMISSIONS.BOOKING_CREATE,
    PERMISSIONS.BOOKING_VIEW,
    PERMISSIONS.BOOKING_UPDATE,

    PERMISSIONS.JOB_CREATE,
    PERMISSIONS.JOB_VIEW,
    PERMISSIONS.JOB_UPDATE,

    PERMISSIONS.QUOTE_CREATE,
    PERMISSIONS.QUOTE_VIEW,
    PERMISSIONS.QUOTE_UPDATE,

    PERMISSIONS.INVOICE_VIEW,

    PERMISSIONS.PAYMENT_VIEW,

    PERMISSIONS.ANALYTICS_VIEW,
  ],

  staff: [
    PERMISSIONS.CUSTOMER_VIEW,

    PERMISSIONS.SERVICE_VIEW,

    PERMISSIONS.BOOKING_VIEW,
    PERMISSIONS.BOOKING_UPDATE,

    PERMISSIONS.JOB_VIEW,
    PERMISSIONS.JOB_UPDATE,

    PERMISSIONS.QUOTE_VIEW,

    PERMISSIONS.INVOICE_VIEW,
  ],

  viewer: [
    PERMISSIONS.ORGANIZATION_VIEW,
    PERMISSIONS.CUSTOMER_VIEW,
    PERMISSIONS.SERVICE_VIEW,
    PERMISSIONS.STAFF_VIEW,
    PERMISSIONS.BOOKING_VIEW,
    PERMISSIONS.JOB_VIEW,
    PERMISSIONS.QUOTE_VIEW,
    PERMISSIONS.INVOICE_VIEW,
    PERMISSIONS.PAYMENT_VIEW,
    PERMISSIONS.ANALYTICS_VIEW,
  ],
};

module.exports = ROLE_PERMISSIONS;